item {
    id: 1
    name: 'driver'
}

item {
    id: 2
    name: 'team'
}

item {
    id: 3
    name: 'lap'
}

item {
    id: 4
    name: 'soft'
}

item {
    id: 5
    name: 'medium'
}

item {
    id: 6
    name: 'hard'
}

item {
    id: 7
    name: 'inter'
}